SQLRelayCommand sqlrcom = (SQLRelayComand)sqlrcon.CreateCommand();
sqlrcom.CommandText = "begin exampleproc(:in1,:in2,:in3,:out1); end";
sqlrcom.Parameters.Add("in1",1);
sqlrcom.Parameters.Add("in2",1.1);
sqlrcom.Parameters.Add("in3","hello");
SQLRelayParameter out1 = new SQLRelayParameter();
out1.ParameterName = "out1";
out1.Direction = ParameterDirection.Output;
out1.DbType = DbType.Int64;
sqlrcom.Parameters.Add(out1);
sqlrcom.ExecuteNonQuery();
Int64 result = Convert.ToInt64(out1.Value);
