$cur->prepareQuery("execute procedure exampleproc ?, ?, ?");
$cur->inputBind("1",1);
$cur->inputBind("2",1.1,2,1);
$cur->inputBind("3","hello");
$cur->defineOutputBindInteger("1");
$cur->defineOutputBindDouble("2");
$cur->defineOutputBindString("3",20);
$cur->executeQuery();
my $out1=$cur->getOutputBindInteger("1");
my $out2=$cur->getOutputBindDouble("2");
my $out3=$cur->getOutputBindString("3");
