my $sth=$dbh->prepare("call exampleproc(?,?,?,?,?,?)");
$sth->bind_param("1",1);
$sth->bind_param("2",1.1,2,1);
$sth->bind_param("3","hello");
my $out1;
my $out2;
my $out3;
$sth->bind_param_inout("4",\$out1,25);
$sth->bind_param_inout("5",\$out2,25);
$sth->bind_param_inout("6",\$out3,25);
$sth->execute();
