sqlrcur_prepareQuery($cur,"exec exampleproc");
sqlrcur_inputBind($cur,"in1",1);
sqlrcur_inputBind($cur,"in2",1.1,2,1);
sqlrcur_inputBind($cur,"in3","hello");
sqlrcur_defineOutputBind($cur,"out1",20);
sqlrcur_defineOutputBind($cur,"out2",20);
sqlrcur_defineOutputBind($cur,"out3",20);
sqlrcur_executeQuery($cur);
$out1=sqlrcur_getOutputBind($cur,"out1");
$out2=sqlrcur_getOutputBind($cur,"out2");
$out3=sqlrcur_getOutputBind($cur,"out3");
