#!/bin/sh

source rpminfo

sed -e "s|RUBYARCH|$RUBYARCH|" \
-e "s|RUBYPREFIX|$RUBYPREFIX|" \
-e "s|RUBYVERSION|$RUBYVERSION|" \
-e "s|PERLSITELIBEXP|$PERLSITELIBEXP|" \
-e "s|PERLSITEARCHEXP|$PERLSITEARCHEXP|" \
-e "s|PERLINSTALLMAN3DIR|$PERLINSTALLMAN3DIR|" \
-e "s|PERLMAN3EXT|$PERLMAN3EXT|" \
-e "s|PERLVERSION|$PERLVERSION|" \
-e "s|\${prefix}|%{prefix}|" \
-e "s|\${exec_prefix}|%{exec_prefix}|" \
-e "s|\${localstatedir}|%{localstatedir}|" \
sqlrelay.spec.in > sqlrelay.spec
