#!/bin/sh

if ( test -z "$1" )
then
	echo "usage: dropintest [mysql|postgresql]"
	exit
fi

if ( test "$1" = "mysql" )
then
	export LD_PRELOAD=/usr/local/firstworks/lib/libmysql51sqlrelay.so
	./mysql
fi


if ( test "$1" = "postgresql" )
then
	export LD_PRELOAD=/usr/local/firstworks/lib/libpqsqlrelay.so
	./postgresql
fi
