include Makefile

rpminfo:
	echo "PREFIX=$(PREFIX)" >> ../../../../rpminfo
	echo "PERLSITELIBEXP=$(SITELIBEXP)" >> ../../../../rpminfo
	echo "PERLSITEARCHEXP=$(SITEARCHEXP)" >> ../../../../rpminfo
	echo "PERLINSTALLMAN3DIR=$(INSTALLMAN3DIR)" >> ../../../../rpminfo
	echo "PERLMAN3EXT=$(MAN3EXT)" >> ../../../../rpminfo
	echo "PERLVERSION=$(SITELIBEXP)" | sed -e "s/=.*site_perl\//=/" >> ../../../../rpminfo
	chmod 666 ../../../../rpminfo
