.TH sqlr-ipclean 8 "2002-06-07" "release left-over IPC resources" SQL\ Relay

.SH NAME
sqlr-ipclean \- release left-over IPC resources

.SH SYNOPSIS
.B sqlr-ipclean

.SH DESCRIPTION
The
.B sqlr-ipclean
program is provided to clean up IPC Resources such as shared memory
and semaphores, which may still be allocated after an SQL Relay crash.

This script is called from the SQL Relay init script after stopping SQL
Relay, but may be useful in its own right.

Any resource owned by the user \fIsqlrelay\fR is released.

.SH SEE ALSO
\fBfields\fP(1),
\fBquery\fP(1),
\fBsqlr-config-gtk\fP(1),
\fBsqlrsh\fP(1),
\fBipcs\fP(8),
\fBipcrm\fP(8),
\fBsqlr-cachemanager\fP(8),
\fBsqlr-connection\fP(8),
\fBsqlr-listener\fP(8),
\fBsqlr-scaler\fP(8),
#\fBsqlr-ipclean\fP(8),
\fBsqlr-start\fP(8),
\fBsqlr-stop\fP(8),
and the documentation in /usr/share/doc/sqlrelay.

.SH AUTHOR
This manual page was written by Florian Weps <fweps@greenmail.ch>,
for the Debian GNU/Linux system (but may be used by others).
