.\"Created with GNOME Manpages Editor Wizard
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH sqlr-connection 8 "11 17, 2001" "Setting Up a Connection"

.SH NAME
sqlr-connection \- Setting up a connection to a database server

.SH SYNOPSIS
.B sqlr-connection
[\fB\-id\fP \fIID\fP]
[\fB\-config\fP \fICONFIGFILE\fP]
[\fB\-connectionid\fP  \fIONNECTIONID\fP]

.SH DESCRIPTION
To estabish a connection, run one of the 
.B sqlr-connection
daemons.

.SH OPTIONS
\fICONFIGFILE\fP is the configuration file to use when starting the
daemon. The default configuration file is \fB/etc/sqlrelay/sqlrelay.conf\fP.

\fIID\fP is just an identifier. Starting multiple connections with the
same \fIID\fP make them available as a pool of connections. The more
connections you start, the more queries can be executed in
parallel. In addition, the \fIID\fP argument specifies which config
file entry to use.

\fICONNECTIONID\fP is another identifier. When using replicated or
clustered databases, within a pool of connections, some connections
will connected to 1 machine and some will connect to another. This
argument tells the connection daemon which machine to connect to. When
not using clustered or replicated databases, this id will be the same
for every connection in the pool.

.SH FILES
/etc/sqlrelay/sqlrelay.conf

.SH AUTHOR
This manual page was written by Andreas Tille <tille@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
