include ../../../../config.mk

all: makefile
	if ( test ! -r blib/lib/DBD/SQLRelay.pm ); then \
		$(MAKE); \
	fi

clean: makefile
	$(MAKE) realclean
	$(RM) Makefile.old

rebuild: clean all

install:
	$(MAKE) install

uninstall:
	if ( test ! -r Makefile ); then \
		$(PERL) Makefile.PL; \
		$(MAKE) uninstall; \
		$(MAKE) clean; \
		$(RM) Makefile.old; \
	else \
		$(MAKE) uninstall; \
	fi

makefile:
	if ( test ! -r Makefile ); then \
		$(PERL) Makefile.PL; \
	fi
