package com.firstworks.sql;

import java.sql.*;

public class SQLRelayStatement implements Statement {

	public void 	addBatch(String sql) throws SQLException {
	}

	public void 	cancel() throws SQLException {
	}

	public void 	clearBatch() throws SQLException {
	}

	public void 	clearWarnings() throws SQLException {
	}

	public void 	close() throws SQLException {
	}

	public void 	closeOnCompletion() throws SQLException {
	}

	public boolean 	execute(String sql) throws SQLException {
		return false;
	}

	public boolean 	execute(String sql, int autoGeneratedKeys)
						throws SQLException {
		return false;
	}

	public boolean 	execute(String sql, int[] columnIndexes)
						throws SQLException {
		return false;
	}

	public boolean 	execute(String sql, String[] columnNames)
						throws SQLException {
		return false;
	}

	public int[] 	executeBatch() throws SQLException {
		return null;
	}

	public ResultSet 	executeQuery(String sql) throws SQLException {
		return null;
	}

	public int 	executeUpdate(String sql) throws SQLException {
		return 0;
	}

	public int 	executeUpdate(String sql, int autoGeneratedKeys)
						throws SQLException {
		return 0;
	}

	public int 	executeUpdate(String sql, int[] columnIndexes)
						throws SQLException {
		return 0;
	}

	public int 	executeUpdate(String sql, String[] columnNames)
						throws SQLException {
		return 0;
	}

	public Connection 	getConnection() throws SQLException {
		return null;
	}

	public int 	getFetchDirection() throws SQLException {
		return 0;
	}

	public int 	getFetchSize() throws SQLException {
		return 0;
	}

	public ResultSet 	getGeneratedKeys() throws SQLException {
		return null;
	}

	public int 	getMaxFieldSize() throws SQLException {
		return 0;
	}

	public int 	getMaxRows() throws SQLException {
		return 0;
	}

	public boolean 	getMoreResults() throws SQLException {
		return false;
	}

	public boolean 	getMoreResults(int current) throws SQLException {
		return false;
	}

	public int 	getQueryTimeout() throws SQLException {
		return 0;
	}

	public ResultSet 	getResultSet() throws SQLException {
		return null;
	}

	public int 	getResultSetConcurrency() throws SQLException {
		return 0;
	}

	public int 	getResultSetHoldability() throws SQLException {
		return 0;
	}

	public int 	getResultSetType() throws SQLException {
		return 0;
	}

	public int 	getUpdateCount() throws SQLException {
		return 0;
	}

	public SQLWarning 	getWarnings() throws SQLException {
		return null;
	}

	public boolean 	isClosed() throws SQLException {
		return false;
	}

	public boolean 	isCloseOnCompletion() throws SQLException {
		return false;
	}

	public boolean 	isPoolable() throws SQLException {
		return false;
	}

	public void 	setCursorName(String name) throws SQLException {
	}

	public void 	setEscapeProcessing(boolean enable)
						throws SQLException {
	}

	public void 	setFetchDirection(int direction) throws SQLException {
	}

	public void 	setFetchSize(int rows) throws SQLException {
	}

	public void 	setMaxFieldSize(int max) throws SQLException {
	}

	public void 	setMaxRows(int max) throws SQLException {
	}

	public void 	setPoolable(boolean poolable) throws SQLException {
	}

	public void 	setQueryTimeout(int seconds) throws SQLException {
	}

	public boolean	isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	public <T> T	unwrap(Class<T> iface) throws SQLException {
		return null;
	}
};
