.TH sqlr-config-gtk 1 "2002-06-10" "SQL Relay configuration GUI" "SQL Relay"

.SH NAME
sqlr-config-gtk \- SQL Relay configuration GUI

.SH SYNOPSIS
.B sqlr-config-gtk

.SH DESCRIPTION
.B sqlr-config-gtk
can be used to configure SQL Relay, but you can also edit the configuration
file by hand.  The GTK+ interface is quite self explanatory.

.SH SEE ALSO
\fBfields\fP(1),
\fBquery\fP(1),
\#\fBsqlr-config-gtk\fP(1),
\fBsqlrsh\fP(1),
\fBsqlr-cachemanager\fP(8),
\fBsqlr-connection\fP(8),
\fBsqlr-listener\fP(8),
\fBsqlr-scaler\fP(8),
\fBsqlr-start\fP(8),
\fBsqlr-stop\fP(8),
and the documentation in /usr/share/doc/sqlrelay.

.SH AUTHORS
This manual page was written by Andreas Tille <tille@debian.org> and
Florian M. Weps <fweps@pop.agri.ch>, for the Debian GNU/Linux system
(but may be used by others).
