.TH sqlr-fields 1 "2002-06-10" "list fields in a table" SQL\ Relay

.SH NAME
sqlr-fields \- list fields in a table

.SH SYNOPSIS
.B sqlr-fields
-host \fIhost\fR -port \fIport\fR -socket \fIsocket\fR -user \fIuser\fR -password \fIpasswd\fR -table \fItable\fR
.br
.B sqlr-fields
[-config \fIconfigfile\fR] -id \fIid\fR -table \fItable\fR

.SH DESCRIPTION
The
.B sqlr-fields
command returns a comma seperated list of the fields in the table
specified by the \fItable\fR argument to standard output.

.SH OPTIONS
.TP
\fB-host\fR \fIhost\fR
hostname of the machine running the listener daemon
.TP
\fB-port\fR \fIport\fR
port number the listener daemon is listening on, for local or remote connections
.TP
\fB-socket\fR \fIsocket\fR
socket the listener daemon is listening on, for local connections
.TP
\fB-user\fR \fIuser\fR
SQL Relay user name (as per config file)
.TP
\fB-password\fR \fIpasswd\fR
SQL Relay password (as per config file)
.TP
\fB-config\fR \fIconfigfile\fR
config file to use (default /etc/sqlrelay/sqlrelay.conf)
.TP
\fB-id\fR \fIid\fR
instance to use (as per config file)
.TP
\fB-table\fR \fItable\fR
table to be described

.SH EXAMPLES
.TP
\fBsqlr-fields -socket /tmp/examplesocket -user fred -password secret -table tbl\fR
Connect to the SQL Relay listener daemon running on the local
machine, with socket \fB/tmp/examplesocket\fR, as user \fBfred\fR,
with password \fBsecret\fR, and return the fields in table \fBtbl\fR.
.TP
\fBsqlr-fields -host dbsvr -port 9000 -user fred -password secret -table tbl\fR
Connect to the SQL Relay listener daemon running on the remote
machine \fBdbsvr\fR, on port \fB9000\fR, as user \fBfred\fR,
with password \fBsecret\fR, and return the fields in table \fBtbl\fR.
.TP
\fBsqlr-fields -id example -table tbl\fR
Connect to the SQL Relay listener daemon for instance \fBexample\fR
(as defined in /etc/sqlrelay/sqlrelay.conf), and return the fields
in table \fBtbl\fR.

.SH SEE ALSO
\#\fBsqlr-fields\fP(1),
\fBsqlr-query\fP(1),
\fBsqlrsh\fP(1),
\fBsqlr-cachemanager\fP(8),
\fBsqlr-connection\fP(8),
\fBsqlr-listener\fP(8),
\fBsqlr-scaler\fP(8),
\fBsqlr-start\fP(8),
\fBsqlr-stop\fP(8),
and the documentation in /usr/share/doc/sqlrelay.

.SH AUTHORS
This manual page was written by Andreas Tille <tille@debian.org> and
Florian M. Weps <fweps@pop.agri.ch>, for the Debian GNU/Linux system
(but may be used by others).
