top_builddir = ../../../..

include ../../../../config.mk

all:

install:
	$(INSTALL) -m 644 sqlrelay/sqlrclientwrapper.h $(incdir)/sqlrelay

uninstall:
	$(RM) $(incdir)/sqlrclientwrapper.h
	$(RM) $(incdir)/sqlrelay/sqlrclientwrapper.h
